name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH to server and update container
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/dekant/app/tg-claude-bot
          # Создаем или обновляем файл .env с переменными окружения из GitHub Secrets
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
          echo "CLAUDE_API_KEY=${{ secrets.CLAUDE_API_KEY }}" >> .env
          echo "CLAUDE_MODEL=${{ secrets.CLAUDE_MODEL }}" >> .env
          
          git pull origin main
          docker-compose down
          docker-compose build --no-cache 
          docker-compose up -d
